---
- name: gather facts
  setup:

- name: Print environment settings
  debug:
    msg: "Setting up {{ env }} environment"

# https://askubuntu.com/a/211531/501568
- name: Install HTTPS package for Aptitude
  become: true
  apt:
    name: apt-transport-https

- name: Add Node key
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Get distribution codename
  shell: lsb_release -c --short
  register: distro_codename

- name: Add Node repository
  become: true
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_6.x {{ distro_codename.stdout }} main"
    state: present

- name: Remove apache server
  become: true
  apt:
    name: apache2
    state: absent

#- include: hostname.yml
- include: tools.yml
